name: Build and Test (With Coverage)

on:
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        if: success()

      - name: Setup PHP with coverage driver
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.16'
          coverage: pcov

      - name: setup application
        if: success()
        run: |
          sudo service mysql start
          php -v
          cp .env.testing.example .env.testing
          mysql -uroot -proot -e "CREATE DATABASE nago_test;"
          composer install --no-interaction
          php artisan --env=testing key:generate
          php artisan migrate
          php artisan route:cache
          mkdir -p storage/logs && touch storage/logs/laravel.log

      - name: PHPUnit tests with coverage
        if: success() && github.event.pull_request.draft == false
        run: composer test-coverage

      - name: upload coverage to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
