name: Pull Request Stats

on:
  pull_request:
    types: [opened]

jobs:
  stats:
    if: contains('pr-stats/', github.base_ref)
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          sort-by: 'COMMENTS'
