name: Pull Request Stats

on:
  pull_request:
    branches:
      - 'pr-stats/**'
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          sort-by: 'COMMENTS'
