name: Pull Request Stats

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  stats:
    if: startsWith(github.ref_name, 'pr-stats')
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          sort-by: 'COMMENTS'
